### PR TITLE
#5 refactor pages/articles

### LINKED ISSUE #5: Better Approach to use `useEffect`
## Description
Personal opinion. But I think we should only set the data in the useEffect to any state rather than using tags. And map/loop over that data in jsx for that page.
For example, `pages/articles.tsx` will look something like

```
const Articles: NextPage = () => {
    const [articles, setArticles] = useState([])
    // adding a loader will be good (if using redux then can use builder's pending/fulfilled/rejected for that)
    const [loading, setLoading] = useState(false)

    useEffect(() => {
        setLoading(true)
        listArticles()
            .then((data) => {
                    let articles_data = data.map((article: any) => {
                        let created_at =  new Date(article.created_at)
                        return {
                           ...article,
                           created_at
                        }
                    })
                    setArticles(articles_data)
                    setLoading(false)
               }
            );
    }, []);

   if (loading) {
        return <div>Loading....</div>
   }

    return <> // Can use <React.Fragment> if need to add any attribute
        <div className={styles.container}>
            {articles.length > 0 ? articles.map(article => (
                  <div key={article.id}>
                        <p>ID: {article.id}</p>
                        <p>Title: {article.title}</p>
                        <p>Description: {article.description}</p>
                        <p>Creator: {article.creator}</p>
                        <p>Created at: {created_at.toISOString()}</p>
                  </div>
             ))  : <h1>No article found</h1>}
        </div>
    </>
};

export default Articles
```
What do you think? 🤔

### PR DESCRIPTION
**Pull request by jinwoo1225**
# Just do some fancy work

- refactor: add articles
- feat: add some css

this closes #5

### CODE REVIEW

**Comment by jinwoo1225** [comment]
closes #5

**Comment by jinwoo1225** [comment]
@NikhilSharma03 just did it! I'm trying to add you as a reviewer but there's no way to do it. 🤔 
I think Next.js is such cool product don't you think?

thanks to you my fancy dashboard is finally here 🤣 

Screen Shot 2022-08-22 at 11 08 59 PM

**Comment by NikhilSharma03** [comment]
Yeah, I think you can tag anyone for review only if the user is either a contributor/collaborator.

Yes, I have been using Next.js lately for blockchain projects, must say it's really amazing. 
The best part is very easy to deploy using Vercel. 😄 🚀 

🤣🤣 Dark Mode is life for Developers. Is it a testing project (for testing Nextjs)?

**Review by NikhilSharma03 — APPROVED** [review]
LGTM 🚀

**Comment by jinwoo1225** [comment]
site without darkmode is meaningless 😎 (i think 😂) I might try to use vercel to deploy this project. thanks 🤙

**Comment by jinwoo1225** [comment]
+ im testing nextjs for my next project :)

**Comment by NikhilSharma03** [comment]
I see. Let me know if i can help. ✌️

**Pull request merged**
